---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/comments/create":
    parameters:
    - name: X-Token
      in: header
      schema:
        type: string
    post:
      summary: Create a comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/v1/comments":
    parameters:
    - name: X-Token
      in: header
      schema:
        type: string
    get:
      summary: Get all comments
      tags:
      - comments
      responses:
        '201':
          description: comments found
        '404':
          description: comments not found
  "/api/v1/posts":
    post:
      summary: Creates a post
      tags:
      - posts
      parameters: []
      responses:
        '201':
          description: post created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
              required:
              - title
              - text
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
